schema_version = "1.0.0"

id = "MetahumanToManny"
version = "1.0.1"
name = "MetaHumanToManny"
tagline = "Clean up MetaHuman meshes and match them to UE5 Manny"
maintainer = "hakanerunsal2@gmail.com"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
